name: learn-space-app # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: LearnSpace Explorer
summary: Discover science and space facts interactively.
description: A fun and educational tool for students to learn about the cosmos, satellites, planets, and physics through mini games and interactive modules.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  learn-space-app:
    command: bin/learn-space-app-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  learn-space-app:
    plugin: dump
    source: .
    organize:
      learn-space-app-bin: bin/
